apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-certhub-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: certhub-server
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
