apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-certhub-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: certhub-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
