{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-certhub-operator-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: certhub-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: certhub-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
{{- end }}
